### SNS Service API Tests - Instagram 인사이트 (간단 예시)

### 공통 변수
@authToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYXJhdG82ODY4QG5hdmVyLmNvbSIsInR5cCI6ImFjY2VzcyIsInVzZXJObyI6MjAsInVzZXJUeXBlIjoiVXNlciIsImlhdCI6MTc1NjQ1MDYyMywiZXhwIjoxNzU2NDU0MjIzfQ.CdJw2FWyDXQwLABUbSzJydP6ou6QsAIqjb6BDvigD5g
@baseUrl = http://localhost:8000/api/v1/sns-service
@testUserId = 20
@testInstagramId = 17841475913854291



### 분석 데이터 조회 (예시 요청)
# 권한: User, Admin
# 설명: 특정 Instagram 계정의 분석 데이터를 조회합니다.
GET {{baseUrl}}/instagram/insights/analysis-data?instagram_id={{testInstagramId}}
Authorization: Bearer {{authToken}}

### 예상 응답
# 200 OK
# {
#   "code": "2000",
#   "message": "OK",
#   "message_code": null,
#   "data": [  {
#      "month": "2025-07-01",
#      "shares": "0",
#      "likes": "1",
#      "comments": "13",
#      "views": "3",
#      "reach": "0"
#    }, .. ]
# }

### 팔로워 히스토리 조회 (예시 요청)
# 권한: User, Admin
# 설명: 특정 Instagram 계정의 팔로워 히스토리를 조회합니다.
GET {{baseUrl}}/instagram/insights/follower-history?instagram_id={{testInstagramId}}
Authorization: Bearer {{authToken}}

### 예상 응답
# 200 OK
# {
#   "code": "2000",
#   "message": "OK",
#   "message_code": null,
#   "data": [ {
#      "instagram_id": "17841475913854291",
#      "stat_month": "2025-06-01",
#      "total_followers": "5"
#    }, ...]
# }

### 참여도 데이터 조회 (예시 요청)
# 권한: User, Admin
# 설명: 특정 Instagram 계정의 참여도 데이터를 조회합니다.
GET {{baseUrl}}/instagram/insights/engagement?instagram_id={{testInstagramId}}
Authorization: Bearer {{authToken}}

### 예상 응답
# 200 OK
# {
#   "code": "2000",
#   "message": "OK",
#   "message_code": null,
#   "data": {
#    "like_rate": 19.51219512195122,
#    "comment_rate": 80.48780487804879,
#    "share_rate": 0.0
#  }
# }


